version: '3.1'

services:
#  demo-producer:
#    container_name: demo-producer
#    image: demo-producer
#    #    environment:
#    #      - DB_SERVER=db
#    ports:
#      - "8080:8080"
#    build:
#      context: ./demo-producer
#      dockerfile: Dockerfile
##    depends_on:
##      - db
#
#  demo-consumer:
#    container_name: demo-consumer
#    image: demo-consumer
##    environment:
##      - DB_SERVER=db
#    ports:
#      - "8081:8081"
#    build:
#      context: ./demo-consumer
#      dockerfile: Dockerfile
##    depends_on:
##      - db

networks:

#volumes:
